RELATIVE_PATH_TO_DATA_JSON = "Tools/data.json"
RELATIVE_PATH_TO_TEST_DATA_JSON = "Tools/TestData/test_data.json"
RELATIVE_PATH_TO_LOG_FILE = "Logs/app.log"
RELATIVE_PATH_TO_SYSTEM_ID_FILE = "Tools/System/material_ids.txt"

MATERIALS_JSON_KEY = "materials"

DEFAULT_MATERIALS_DICT = {MATERIALS_JSON_KEY: []}

PROTECTED_MATERIAL_ID = "_id"
PROTECTED_MATERIAL_NAME = "_name"
PROTECTED_MATERIAL_PRICE = "_price"

MATERIAL_ID = "id"
MATERIAL_NAME = "name"
MATERIAL_PRICE = "price"

START_MATERIAL_ID_VALUE = 1

ENCODING_TYPE = "utf-8"
INDENT = 3